### PR TITLE
added css gradient and rounded corner

### LINKED ISSUE #26: [Feature] Improve UI design
**Is your feature request related to a problem? Please describe.**
The design doesn't look good at all, it would be nice to change it to something more pleasing.

**Describe the solution you'd like**
An animated gradient for the background similar to the one bellow would be nice to have. The animation has to be slow, something like a wave.
image

The button may be changed as well, maybe having rounded corners and to fit well with the background.
Probably the font color has to change as well.
Also the loading bar will have to fit with the background.
This [tool](https://webaim.org/resources/contrastchecker/) can be used to check if the contrast is right.

### PR DESCRIPTION
**Pull request by amardeep911**
ISSUE #26 

Added Rounded Corner-
image
Added Css gradient-
image
Added font color
image

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
Please add the gradient I put in the issue and remove the colorful gradient

**Comment by amardeep911** [comment]
image
Gradient fix done

**Comment by eduardconstantin** [comment]
Please add this as the main background color `#b0f3ae` and also change the font color because it hurt my eyes.

**Comment by amardeep911** [comment]
Main Background Fixed
image
Font Color Changed
image
Button Color Smoothend
image

**Comment by eduardconstantin** [comment]
Thank you!
@all-contributors please add @amardeep911 for code

**Pull request merged**
