### PR TITLE
Added code of conduct file

### LINKED ISSUE #2: Create code of coduct file
Add a CODE_OF_CONDUCT.md file to the project

### PR DESCRIPTION
**Pull request by ghost**
Hi @eduardconstantin, I have added the Code of Conduct markdown file. Under the enforcement section the contact method is missing, please let me know if you would like to add a method in particular.

### CODE REVIEW

**Comment by eduardconstantin** [comment]
I will add it. Thank you!

**Comment by eduardconstantin** [comment]
@all-contributors please add @samc18 for doc

**Comment by ghost** [comment]
Thanks for this opportunity to help out!

**Comment by eduardconstantin** [comment]
You’re welcome! Thank you for your help!

**Pull request merged**
